import type { Metadata } from "next";
import { PageHero } from "@/components/PageHero";
import { Container, Section } from "@/components/ui";
import { FeatureGrid, CtaSection } from "@/components/sections";

export const metadata: Metadata = {
  title: "Learning Platform",
  description:
    "Deliver multilingual courses and on-demand training with SabioCast Learning — AI captions and translations built in.",
};

export default function LearningPage() {
  return (
    <>
      <PageHero
        eyebrow="Learning Platform"
        title="Multilingual courses and on-demand training"
        intro="SabioCast Learning turns your live and recorded sessions into structured, multilingual courses — with AI captions, AI speech translation and per-learner progress tracking."
      />
      <FeatureGrid
        eyebrow="What's included"
        title="Training that reaches everyone"
        features={[
          { title: "Multilingual by default", body: "Every lesson can carry multiple audio languages and caption tracks, generated by AI or human experts." },
          { title: "Structured courses", body: "Group live sessions and VoD into modules, chapters and lessons with a branded catalogue." },
          { title: "Progress & completion", body: "Track per-learner progress, quiz results and completion certificates." },
          { title: "Live and on-demand", body: "Run live cohorts, then publish the recording as a self-paced course automatically." },
          { title: "Access control", body: "Invitation-only, domain-restricted or open enrolment — your choice per course." },
          { title: "Analytics", body: "See which lessons hold attention and where learners drop off." },
        ]}
      />
      <CtaSection heading="Bring your training to every language" />
    </>
  );
}
